### ISSUE TITLE
Registration form is not working, issue with interests

### ISSUE THREAD

**Issue by bikkimahato** [Jebasuthan/React-form-registration#5]
Just shows invalid form
![image](https://user-images.githubusercontent.com/42492682/187037651-51bc24fe-6482-48ef-b6af-e144ba1f3eb1.png)

**Comment by Jebasuthan** [comment]
@bikkimahato The form shows the error message above the submit button. You can you to add interests like below
<img width="801" alt="Screenshot 2022-08-29 at 9 40 25 AM" src="https://user-images.githubusercontent.com/3702438/187121396-bb028c4e-9971-46b8-93ca-9ba231d59a36.png">
.
